version: '2.3'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  app:
      image: data-redis:ni-distroless
      environment:
        - REDIS_HOST=host.docker.internal
      depends_on:
        redis:
          condition: service_started
      mem_limit: 80m
      cpu_shares: 512
#      volumes:
#          - type: bind
#            source: ../report
#            target: /report
volumes:
  redis_data:
    driver: local