version: '2.4'
services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/db/mysql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/mysql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
  petclinic-jpa:
    image: krisfoster/pet-clinic-jpa:openjdk
    mem_limit: 512m
    memswap_limit: 512m
    cpu_count: 2
    cpu_percent: 100
    cpus: 2
    cpuset: 0,1
    ports:
      - "8081:8080"
    depends_on:
      - mysql-server